[package]
name = "enclave"
version.workspace = true
edition.workspace = true

[lib]
name = "enclave"
path = "src/lib.rs"

[[bin]]
name = "enclave"
path = "src/main.rs"

[features]
default = ["mock"]
mock = []
nitro = ["dep:aws-nitro-enclaves-nsm-api"]

[dependencies]
shared = { path = "../shared" }
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
hex = { workspace = true }
serde_bytes = { workspace = true }
dotenvy = { workspace = true }
tower-http = { workspace = true }
rand = "0.8"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto" }
async-trait = "0.1"

aws-nitro-enclaves-nsm-api = { git = "https://github.com/aws/aws-nitro-enclaves-nsm-api", rev = "8ec7eac72bbb2097f1058ee32c13e1ff232f13e8", optional = true }

[dev-dependencies]
tokio = { workspace = true }
tower = { version = "0.4", features = ["util"] }
